# Dynmap-ASkyBlock configuration
#
update:
  # Seconds between checks for Island updates
  period: 300

layer:
  name: "ASkyBlock"
  # Make mobs layer hidden by default
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 0
  # (optional) set minimum zoom level before layer is visible (0 = defalt, always visible)
  minzoom: 0
  
# Set true to show 3D volumes for zones  
use3dregions: false

# Format for popup - substitute values for macros
# Macros are:
# %ownername% - island owner or leader
# %teammembers% - team members
# %islandlevel% - island level
# %owneruuid% - owner's UUID (you probably never want to show this)
infowindow: '<div class=\"infowindow\">Owner <span style="font-weight:bold;">%ownername%<br/></span><br/>Team Members <span style="font-weight:bold;"><br/>%teammembers%</span><br/>Island level<br /><span style="font-weight:bold;">%islandlevel%</span></div>'

islandstyle:
  strokeColor: "#FF0000"
  strokeOpacity: 0.8
  strokeWeight: 3
  fillColor: "#FF0000"
  fillOpacity: 0.35
  
# Optional setting to limit which islands to show, by name of owner
visibleislands: [ ]
  
# Optional setting to hide specific islands, by name of owner
hiddenislands: [ ]

# Optional per-owner overrides for islandstyle - use owner's UUID or name
ownerstyle:
  # tastybento
  tastybento:
    strokeColor: "#00FFFF"
    fillColor: "#00FFFF"
    
# Limit number of islands processed per tick (avoid lag spikes on servers with lots of islands)
updates-per-tick: 300
